import os

print("Add Commit Push with Python")
print()
print("git status:")
print()
os.system("git status")
print()
print("git add -a")
print()
os.system("git add -a")
print()
print('git commit -m "update files"')
print()
os.system('git commit -m "update files"')
print()
print("git push")
print()
os.system("git push")
print()